import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VibeXcode - A collaborative way to vibe and code!!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gradient-to-r from-[#e0c3fc] to-[#8ec5fc] dark:bg-black min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <>
          {children}
          <Footer />
        </>
      </body>
    </html>
  );
}
